In [15]:
#1.Write a NumPy program to multiply two given arrays of same size element-by-element.
import numpy as np
arr1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                    [10, 11, 12]])
result = arr1 * arr2

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nResult of element-wise multiplication:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Result of element-wise multiplication:
[[ 7 16 27]
 [40 55 72]]


In [2]:
#2.Write a NumPy program to find the missing data in a given array.
import numpy as np
arr = np.array([1, 2, np.nan, 4, np.nan, 6, 7, np.nan])
missing_indices = np.isnan(arr)
missing_values = arr[missing_indices]

print("Array with missing data:")
print(arr)

print("\nIndices of missing data:")
print(missing_indices)

print("\nMissing values:")
print(missing_values)


Array with missing data:
[ 1.  2. nan  4. nan  6.  7. nan]

Indices of missing data:
[False False  True False  True False False  True]

Missing values:
[nan nan nan]


In [ ]:
#3.Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 3, 7, 8, 9])

result = np.in1d(arr1, arr2)
print(result)


[ True False  True False False]


In [ ]:
#4.Write a NumPy program to save a NumPy array to a text file.
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

filename = 'arr_data.txt'
np.savetxt(filename, array, fmt='%d')

print("Array saved to", filename)


Array saved to arr_data.txt


In [ ]:
#5.Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive.
import numpy as np
array = np.linspace(2.5, 6.5, 30)

print("1-D array of 30 evenly spaced elements between 2.5 and 6.5, inclusive:")
print(array)


1-D array of 30 evenly spaced elements between 2.5 and 6.5, inclusive:
[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [ ]:
#Introduction to Pandas (Series and Dataframes)
#1.Write a Pandas program to convert Series of lists to one Series.
import pandas as pd
series_of_lists = pd.Series([[1, 2, 3], [4, 5], [6, 7, 8]])
one_series = series_of_lists.apply(pd.Series).stack().reset_index(drop=True)
print("Series of lists:")
print(series_of_lists)
print("\nOne Series:")
print(one_series)


Series of lists:
0    [1, 2, 3]
1       [4, 5]
2    [6, 7, 8]
dtype: object

One Series:
0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    8.0
dtype: float64


In [ ]:
#2.Write a Pandas program to create a subset of a given series based on value and condition.
import pandas as pd
data = {'A': [10, 20, 30, 40, 50],
        'B': [5, 15, 25, 35, 45]}
series = pd.Series(data['A'], index=['a', 'b', 'c', 'd', 'e'])
condition = series > 25
subset = series[condition]

print("Original Series:")
print(series)

print("\nSubset based on condition (values > 25):")
print(subset)


Original Series:
a    10
b    20
c    30
d    40
e    50
dtype: int64

Subset based on condition (values > 25):
c    30
d    40
e    50
dtype: int64


In [ ]:
#3. Write a Pandas program to display most frequent value in a given series and replace everything else as other in the series.
import pandas as pd

# Create a sample Series
series = pd.Series(['A', 'B', 'A', 'C', 'A', 'B', 'A', 'B', 'B'])

# Find the most frequent value
most_frequent_value = series.mode()[0]

# Replace everything else as 'Other'
series[series != most_frequent_value] = 'Other'

print("Original Series:")
print(series)


Original Series:
0        A
1    Other
2        A
3    Other
4        A
5    Other
6        A
7    Other
8    Other
dtype: object


In [ ]:
#4.Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.
import pandas as pd
series = pd.Series([10, 15, 20, 25, 30, 35, 40, 45, 50])
positions = series.index[series % 5 == 0]

print("Original Series:")
print(series)

print("\nPositions of numbers that are multiples of 5:")
print(positions)

Original Series:
0    10
1    15
2    20
3    25
4    30
5    35
6    40
7    45
8    50
dtype: int64

Positions of numbers that are multiples of 5:
Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')


In [3]:
#5.Write a Pandas program to calculate the number of characters in each word in a given series.
import pandas as pd
words_series = pd.Series(['apple', 'banana', 'orange', 'grape', 'kiwi'])

word_lengths = words_series.str.len()

word_length_df = pd.DataFrame({'Word': words_series, 'Length': word_lengths})

print(word_length_df)


     Word  Length
0   apple       5
1  banana       6
2  orange       6
3   grape       5
4    kiwi       4


In [17]:
#6.Write a Pandas program to convert year-month string to dates adding a specified day of the month.
import pandas as pd
year_month_strings = ['2023-01', '2023-02', '2023-03']

specified_day = 15

dates_with_specified_day = pd.to_datetime([year_month + '-' + str(specified_day) for year_month in year_month_strings])
print(dates_with_specified_day)



DatetimeIndex(['2023-01-15', '2023-02-15', '2023-03-15'], dtype='datetime64[ns]', freq=None)


In [4]:
#7.Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data, index=['Person1', 'Person2', 'Person3', 'Person4'])


print(df)


            Name  Age         City
Person1    Alice   25     New York
Person2      Bob   30  Los Angeles
Person3  Charlie   35      Chicago
Person4    David   40      Houston


In [6]:
#8.Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Attempts': [3, 1, 4, 2]
}

df = pd.DataFrame(data)

result = df[df['Attempts'] > 2]

print(result)


      Name  Attempts
0    Alice         3
2  Charlie         4


In [8]:
#9.Write a Pandas program to append a new row k to data frame with given values for each column. Now delete the new row and return the original DataFrame.
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40]
}
df = pd.DataFrame(data)

new_row = {'Name': 'Emily', 'Age': 27}

df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

print(df)

df = df.drop(index=len(df) - 1)

print(df)


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4    Emily   27
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40


In [19]:
#10.Write a Pandas program to sort the DataFrame first by name in descending order,then by score in ascending order.
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Score': [80, 75, 90, 85]
}
df = pd.DataFrame(data)
df_sorted = df.sort_values(by=['Name', 'Score'], ascending=[False, True])

print(df_sorted)

      Name  Attempts  Score
0    Alice         1     80
1      Bob         3     65
2  Charlie         2     90
3    David         4     75
      Name  Attempts  Score
3    David         4     75
2  Charlie         2     90
1      Bob         3     65
0    Alice         1     80


In [10]:
#11.Write a Pandas program to replace the qualify column contains the values yes and no with True and False.
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Qualify': ['yes', 'no', 'yes', 'no']
}
df = pd.DataFrame(data)

df['Qualify'] = df['Qualify'].replace({'yes': True, 'no': False})

print(df)


      Name  Qualify
0    Alice     True
1      Bob    False
2  Charlie     True
3    David    False


In [14]:
#12.Write a Pandas program to remove infinite values from a given DataFrame.
import pandas as pd
import numpy as np
data = {
    'A': [1, 2, np.inf, 4],
    'B': [5, 6, 7, 8]
}

df = pd.DataFrame(data)
print(df)
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)
print(df)

     A  B
0  1.0  5
1  2.0  6
2  inf  7
3  4.0  8
     A  B
0  1.0  5
1  2.0  6
3  4.0  8
